// src/app/layout.js
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { cookies } from "next/headers"; // Use server-side check
import { headers } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Real state",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = headers().get("x-next-pathname") || "";

  const isAuthRoute = pathname.startsWith("/auth");

  return (
    <html lang="en">
      <body className={inter.className}>
        {!isAuthRoute && <Header />}
        {children}
        {!isAuthRoute && <Footer />}
      </body>
    </html>
  );
}
